# Generated by Django 5.0 on 2023-12-23 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_choice', models.CharField(choices=[('gpt-3.5-turbo', 'GPT-3.5'), ('gemini-pro', 'Gemini Pro')], default='gpt-3.5-turbo', max_length=20)),
                ('sentence_length', models.IntegerField(choices=[(3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
