# Generated by Django 5.0 on 2023-12-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_preference_sentence_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='model_choice',
            new_name='ai_model',
        ),
    ]
