# Generated by Django 5.0 on 2023-12-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlsummary',
            options={'ordering': ('-created_at',), 'verbose_name': 'URL Summary'},
        ),
    ]
